export const UPDATE_USERS = 'UPDATE_USERS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
export const UPDATE_QUESTION_VIEW = 'UPDATE_QUESTION_VIEW';

export const SET_LOADING = 'SET_LOADING';
